import fs from "fs";
import path from "path";
import { evalService } from "@/services/eval.service";
import { GUARD_CONFIG } from "@/config/guard.config";

async function main() {
  const report = await evalService.run();
  const sweep = await evalService.thresholdSweep();
  const outDir = path.join(process.cwd(), "docs", "eval");
  fs.mkdirSync(outDir, { recursive: true });

  const md = `# Threshold curve

Generated by \`pnpm eval:sweep\`. This report is how Lens proves the guard
policy is tuned, not guessed.

## Current policy

- Policy id: \`${GUARD_CONFIG.policyId}\`
- Similarity floor: \`${GUARD_CONFIG.similarityThreshold}\`
- Confidence floor: \`${GUARD_CONFIG.confidenceThreshold}\`

## Labeled eval

- Top-1 precision: **${report.top1Precision.toFixed(2)}** (${report.correct}/${report.total})
- No-match recall: **${report.noMatchRecall.toFixed(2)}**
- Guard false-refuse rate: **${report.guardFalseRefuseRate.toFixed(2)}**
- Guard false-accept rate: **${report.guardFalseAcceptRate.toFixed(2)}**
- Hard-negative matrix accuracy: **${report.matrix.accuracy.toFixed(2)}** (${report.matrix.correct}/${report.matrix.total})

## Best sweep point

- Similarity: \`${sweep.best.similarityThreshold}\`
- Confidence: \`${sweep.best.confidenceThreshold}\`
- Matrix accuracy: **${sweep.best.accuracy.toFixed(2)}**

## Sweep table

| sim | conf | accuracy |
|---|---:|---:|
${sweep.points
  .map(
    (point) =>
      `| ${point.similarityThreshold.toFixed(2)} | ${point.confidenceThreshold.toFixed(2)} | ${point.accuracy.toFixed(2)} |`
  )
  .join("\n")}
`;

  fs.writeFileSync(path.join(outDir, "threshold-curve.md"), md);
  fs.writeFileSync(
    path.join(outDir, "latest.json"),
    JSON.stringify({ report, sweep }, null, 2)
  );
  console.log(JSON.stringify({ top1Precision: report.top1Precision, best: sweep.best }, null, 2));
  console.log(`wrote ${path.join("docs", "eval", "threshold-curve.md")}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
